// =====================================================
//  Trilha do Código — Dados da Jornada (3 Níveis)
// =====================================================

// Config visual / gamificação dos 3 níveis
// Imagens: Vila → Cidade → Reino (ver public/images/fantasy/README.md)
const JOURNEY_LEVELS = [
  {
    order: 1,
    key: "iniciante",
    id: "nivel-1",
    label: "Nível 1 — Iniciante",
    shortLabel: "I — Iniciante",
    subtitle: "Aprendiz do Código",
    desc: "Aprender a construir aplicações completas entendendo os fundamentos e o papel de cada camada.",
    motto: "Aprender a construir",
    icon: "🌱",
    iconAsset: "public/images/fantasy/icons/icon-village.svg",
    image: "public/images/fantasy/levels/beginner-village.webp",
    imageAlt: "Pequena vila ao amanhecer, estrada entre árvores e riacho — começo da jornada",
    completeMsg: "Os fundamentos foram dominados."
  },
  {
    order: 2,
    key: "intermediario",
    id: "nivel-2",
    label: "Nível 2 — Intermediário",
    shortLabel: "II — Intermediário",
    subtitle: "Cavaleiro da Engenharia",
    desc: "Aprender a construir aplicações profissionais, robustas, seguras, testáveis e preparadas para crescer.",
    motto: "Aprender a construir bem",
    icon: "⚔️",
    iconAsset: "public/images/fantasy/icons/icon-city.svg",
    image: "public/images/fantasy/levels/intermediate-city.webp",
    imageAlt: "Cidade medieval com pontes, torres e guilda integrada à natureza",
    completeMsg: "Você aprendeu a construir sistemas robustos."
  },
  {
    order: 3,
    key: "avancado",
    id: "nivel-3",
    label: "Nível 3 — Avançado",
    shortLabel: "III — Avançado",
    subtitle: "Arquiteto do Reino",
    desc: "Aprender a projetar sistemas, tomar decisões arquiteturais, lidar com escala, resiliência, performance e sistemas distribuídos.",
    motto: "Aprender a projetar sistemas",
    icon: "👑",
    iconAsset: "public/images/fantasy/icons/icon-kingdom.svg",
    image: "public/images/fantasy/levels/advanced-kingdom.webp",
    imageAlt: "Reino monumental com castelo, montanhas, cachoeiras e jardins sob luz majestosa",
    completeMsg: "Você completou a jornada principal e domina os fundamentos de arquitetura de sistemas."
  },
];

const HERO_ASSET = {
  image: "public/images/fantasy/hero/journey-landscape.webp",
  alt: "Vale luminoso com grande árvore, campo florido, rio, vila medieval e castelo ao fundo sob céu azul",
};

// -----------------------------------------------------
//  NÍVEL 1 — INICIANTE (trilha original preservada)
// -----------------------------------------------------
const NIVEL_1_DATA = [
  {
    id: "fundamentos",
    icon: "📜",
    title: "Fundamentos de Programação",
    desc: "Lógica, variáveis, condicionais e laços. A base de todo aventureiro.",
    topics: [
      { id: "f1", label: "Variáveis, tipos e operadores" },
      { id: "f2", label: "Condicionais (if/else, switch)" },
      { id: "f3", label: "Laços (for, while) e iteração" },
      { id: "f4", label: "Funções, escopo e parâmetros" },
      { id: "f5", label: "Arrays e objetos básicos" },
      { id: "f6", label: "Algoritmos simples e debugging" },
    ],
    criteria: [
      { id: "fc1", label: "Resolver 10 exercícios de lógica sem consultar resposta" },
      { id: "fc2", label: "Explicar com suas palavras cada estrutura básica" },
    ]
  },
  {
    id: "js-essencial",
    icon: "⚡",
    title: "JavaScript Essencial",
    desc: "O idioma da web. Domine o JS moderno além da sintaxe.",
    topics: [
      { id: "j1", label: "let/const, desestruturação e spread" },
      { id: "j2", label: "Arrow functions e template literals" },
      { id: "j3", label: "Métodos de array (map, filter, reduce, find)" },
      { id: "j4", label: "Objetos, JSON e cópia rasa/profunda" },
      { id: "j5", label: "Módulos (import/export) e escopo" },
      { id: "j6", label: "Manipulação de DOM básica" },
    ],
    criteria: [
      { id: "jc1", label: "Reescrever 3 exercícios usando métodos funcionais" },
      { id: "jc2", label: "Criar mini-projeto JS sem framework (ex: todo list)" },
    ]
  },
  {
    id: "assincronismo",
    icon: "⏳",
    title: "Assincronismo",
    desc: "O tempo no JavaScript: callbacks, promises e o fluxo do event loop.",
    topics: [
      { id: "a1", label: "Callbacks e callback hell" },
      { id: "a2", label: "Promises (then/catch/finally)" },
      { id: "a3", label: "Async/await e try/catch" },
      { id: "a4", label: "Event Loop, microtasks e setTimeout" },
      { id: "a5", label: "Promise.all / allSettled / race" },
    ],
    criteria: [
      { id: "ac1", label: "Consumir uma API pública com async/await" },
      { id: "ac2", label: "Tratar erros e estados de loading corretamente" },
    ]
  },
  {
    id: "web-http",
    icon: "🌐",
    title: "Web e HTTP",
    desc: "Como a web realmente funciona: requisições, respostas e bastidores.",
    topics: [
      { id: "w1", label: "HTTP: verbos, status codes e headers" },
      { id: "w2", label: "Request/Response e URL/Query params" },
      { id: "w3", label: "REST: recursos, rotas e boas práticas" },
      { id: "w4", label: "Fetch API e JSON" },
      { id: "w5", label: "CORS, cookies e autenticação básica" },
    ],
    criteria: [
      { id: "wc1", label: "Inspecionar requisições no DevTools e explicar cada parte" },
      { id: "wc2", label: "Criar requisições GET/POST/PUT/DELETE para uma API fake" },
    ]
  },
  {
    id: "node-sem-framework",
    icon: "🟢",
    title: "Node.js sem Framework",
    desc: "Node cru: entenda o que os frameworks abstraem.",
    topics: [
      { id: "n1", label: "Node, npm e módulo http nativo" },
      { id: "n2", label: "Criar servidor HTTP na mão (rotas e handlers)" },
      { id: "n3", label: "File System (fs) e streams" },
      { id: "n4", label: "Variáveis de ambiente e .env" },
      { id: "n5", label: "Nodemon, scripts npm e organização" },
    ],
    criteria: [
      { id: "nc1", label: "Servidor com 3 rotas funcionando sem Express" },
      { id: "nc2", label: "Ler/escrever arquivos e servir JSON estático" },
    ]
  },
  {
    id: "banco-sql",
    icon: "🗄️",
    title: "Banco de Dados e SQL",
    desc: "Onde os dados descansam. Modele, consulte e proteja.",
    topics: [
      { id: "b1", label: "Modelo relacional e tipos de dados" },
      { id: "b2", label: "SELECT, WHERE, ORDER BY, LIMIT" },
      { id: "b3", label: "JOINs, GROUP BY e agregações" },
      { id: "b4", label: "INSERT/UPDATE/DELETE e transactions" },
      { id: "b5", label: "Índices, chaves e normalização" },
      { id: "b6", label: "SQLite/Postgres na prática com Node" },
    ],
    criteria: [
      { id: "bc1", label: "Modelar 2 tabelas com relacionamento e popular" },
      { id: "bc2", label: "Escrever 5 queries com JOIN e filtros complexos" },
    ]
  },
  {
    id: "backend-framework",
    icon: "🏰",
    title: "Backend com Framework",
    desc: "Erga as muralhas: Express/Fastify, rotas e camadas.",
    topics: [
      { id: "bf1", label: "Express ou Fastify: setup e middlewares" },
      { id: "bf2", label: "Roteamento, controllers e services" },
      { id: "bf3", label: "Validação (Zod/Joi) e tratamento de erros" },
      { id: "bf4", label: "Conexão com DB e queries parametrizadas" },
      { id: "bf5", label: "Autenticação JWT e rotas protegidas" },
      { id: "bf6", label: "Estrutura em camadas e boas práticas" },
    ],
    criteria: [
      { id: "bfc1", label: "CRUD completo com validação e status codes corretos" },
      { id: "bfc2", label: "Middleware de auth protegendo rotas privadas" },
    ]
  },
  {
    id: "typescript",
    icon: "🔷",
    title: "TypeScript",
    desc: "Armadura para seu código: tipos que protegem sua jornada.",
    topics: [
      { id: "t1", label: "Tipagem básica, interfaces e types" },
      { id: "t2", label: "Generics e utility types" },
      { id: "t3", label: "Tipagem de funções e promises" },
      { id: "t4", label: "TS no Node e no frontend" },
      { id: "t5", label: "ESLint + TSConfig e strict mode" },
    ],
    criteria: [
      { id: "tc1", label: "Migrar um projeto JS para TS sem usar 'any'" },
      { id: "tc2", label: "Criar tipos para requests/responses da API" },
    ]
  },
  {
    id: "frontend-sem-framework",
    icon: "🎨",
    title: "Frontend sem Framework",
    desc: "HTML, CSS e JS puros: a forja onde se tempera o aço.",
    topics: [
      { id: "ff1", label: "HTML semântico e acessibilidade" },
      { id: "ff2", label: "CSS moderno: Flex, Grid e responsivo" },
      { id: "ff3", label: "JS no browser: eventos e DOM" },
      { id: "ff4", label: "Formulários, validação e feedback" },
      { id: "ff5", label: "Fetch no frontend e renderização" },
    ],
    criteria: [
      { id: "ffc1", label: "Página responsiva consumindo sua própria API" },
      { id: "ffc2", label: "Form com validação e estados visuais" },
    ]
  },
  {
    id: "react",
    icon: "⚛️",
    title: "React",
    desc: "Componentes, estado e o ecossistema reativo.",
    topics: [
      { id: "r1", label: "Componentes, props e JSX" },
      { id: "r2", label: "useState, useEffect e ciclo de vida" },
      { id: "r3", label: "Listas, keys e renderização condicional" },
      { id: "r4", label: "React Router e navegação" },
      { id: "r5", label: "Context API / estado global simples" },
      { id: "r6", label: "Vite, build e deploy" },
    ],
    criteria: [
      { id: "rc1", label: "SPA com 3 rotas e consumo de API" },
      { id: "rc2", label: "Gerenciar estado sem prop drilling excessivo" },
    ]
  },
  {
    id: "docker-infra",
    icon: "🐳",
    title: "Docker e Infra",
    desc: "Embarque sua aplicação: containers e ambiente reproduzível.",
    topics: [
      { id: "d1", label: "Docker: imagens, containers e Dockerfile" },
      { id: "d2", label: "Docker Compose (app + db)" },
      { id: "d3", label: "Volumes, networks e variáveis" },
      { id: "d4", label: "Build otimizado e .dockerignore" },
    ],
    criteria: [
      { id: "dc1", label: "Subir app + banco com docker-compose up" },
      { id: "dc2", label: "Dockerfile multi-stage funcionando" },
    ]
  },
  {
    id: "git-testes-deploy",
    icon: "🚀",
    title: "Git, Testes e Deploy",
    desc: "O caminho até a produção: versionamento, testes e entrega.",
    topics: [
      { id: "g1", label: "Git: branches, merge, rebase e PRs" },
      { id: "g2", label: "Testes unitários (Vitest/Jest)" },
      { id: "g3", label: "Testes de integração / E2E básicos" },
      { id: "g4", label: "CI simples (GitHub Actions)" },
      { id: "g5", label: "Deploy (Vercel/Render/Fly) e env vars" },
    ],
    criteria: [
      { id: "gc1", label: "Repositório com histórico limpo e README" },
      { id: "gc2", label: "Pipeline que roda testes a cada push" },
    ]
  },
];

// -----------------------------------------------------
//  NÍVEL 2 — INTERMEDIÁRIO
// -----------------------------------------------------
const NIVEL_2_DATA = [
  {
    id: "n2-ts-avancado",
    icon: "🔷",
    title: "TypeScript Avançado",
    desc: "Domine o sistema de tipos para modelar domínios complexos sem any.",
    topics: [
      { id: "n2t1", label: "Generics" },
      { id: "n2t2", label: "Constraints" },
      { id: "n2t3", label: "Utility Types" },
      { id: "n2t4", label: "Mapped Types" },
      { id: "n2t5", label: "Conditional Types" },
      { id: "n2t6", label: "Discriminated Unions" },
      { id: "n2t7", label: "Type Guards" },
      { id: "n2t8", label: "infer" },
      { id: "n2t9", label: "Overloads" },
      { id: "n2t10", label: "Tipagem de DTOs" },
      { id: "n2t11", label: "Tipagem de APIs" },
      { id: "n2t12", label: "Tipagem de erros" },
      { id: "n2t13", label: "Generics em services e repositories" },
      { id: "n2t14", label: "Inferência vs tipagem explícita" },
    ],
    criteria: [
      { id: "n2tc1", label: "Consigo criar generics úteis" },
      { id: "n2tc2", label: "Consigo modelar estados complexos com unions" },
      { id: "n2tc3", label: "Consigo evitar any" },
      { id: "n2tc4", label: "Consigo criar tipos reutilizáveis" },
      { id: "n2tc5", label: "Consigo entender erros complexos do TypeScript" },
    ]
  },
  {
    id: "n2-backend-profissional",
    icon: "🏰",
    title: "Backend Profissional com Fastify",
    desc: "Estruture backends de médio porte com plugins, hooks e arquitetura modular.",
    topics: [
      { id: "n2b1", label: "Plugins" },
      { id: "n2b2", label: "Hooks" },
      { id: "n2b3", label: "Decorators" },
      { id: "n2b4", label: "Schemas" },
      { id: "n2b5", label: "Validação" },
      { id: "n2b6", label: "Tratamento global de erros" },
      { id: "n2b7", label: "Request context" },
      { id: "n2b8", label: "Logging estruturado" },
      { id: "n2b9", label: "Configuração por ambiente" },
      { id: "n2b10", label: "Versionamento de API" },
      { id: "n2b11", label: "Organização por módulos" },
      { id: "n2b12", label: "Arquitetura modular" },
    ],
    criteria: [
      { id: "n2bc1", label: "Consigo estruturar um backend de médio porte" },
      { id: "n2bc2", label: "Consigo criar plugins" },
      { id: "n2bc3", label: "Consigo separar módulos de domínio" },
      { id: "n2bc4", label: "Consigo criar tratamento global de erros" },
      { id: "n2bc5", label: "Consigo configurar dev, test e prod" },
    ]
  },
  {
    id: "n2-auth",
    icon: "🔐",
    title: "Autenticação e Autorização Avançadas",
    desc: "Segurança real: hash, JWT, OAuth, RBAC e sessões.",
    topics: [
      { id: "n2a1", label: "Hash de senha" },
      { id: "n2a2", label: "bcrypt / argon2" },
      { id: "n2a3", label: "JWT" },
      { id: "n2a4", label: "Access Token" },
      { id: "n2a5", label: "Refresh Token" },
      { id: "n2a6", label: "Cookies HttpOnly" },
      { id: "n2a7", label: "Sessions" },
      { id: "n2a8", label: "OAuth 2.0" },
      { id: "n2a9", label: "OpenID Connect" },
      { id: "n2a10", label: "RBAC" },
      { id: "n2a11", label: "ABAC" },
      { id: "n2a12", label: "Roles" },
      { id: "n2a13", label: "Permissions" },
      { id: "n2a14", label: "Logout seguro" },
      { id: "n2a15", label: "Revogação de sessão" },
      { id: "n2a16", label: "Rotação de refresh token" },
    ],
    criteria: [
      { id: "n2ac1", label: "Consigo implementar login completo" },
      { id: "n2ac2", label: "Consigo explicar JWT" },
      { id: "n2ac3", label: "Consigo diferenciar OAuth e OpenID Connect" },
      { id: "n2ac4", label: "Consigo implementar roles e permissões" },
      { id: "n2ac5", label: "Consigo proteger rotas corretamente" },
    ]
  },
  {
    id: "n2-bd-intermediario",
    icon: "🗄️",
    title: "Banco de Dados Intermediário",
    desc: "Performance, transações e modelagem para aplicações reais.",
    topics: [
      { id: "n2bd1", label: "Índices compostos" },
      { id: "n2bd2", label: "Índices parciais" },
      { id: "n2bd3", label: "EXPLAIN" },
      { id: "n2bd4", label: "EXPLAIN ANALYZE" },
      { id: "n2bd5", label: "Otimização de queries" },
      { id: "n2bd6", label: "Subqueries" },
      { id: "n2bd7", label: "CTE" },
      { id: "n2bd8", label: "Window Functions" },
      { id: "n2bd9", label: "Transactions" },
      { id: "n2bd10", label: "Isolation Levels" },
      { id: "n2bd11", label: "Locks" },
      { id: "n2bd12", label: "Deadlocks" },
      { id: "n2bd13", label: "Constraints avançadas" },
      { id: "n2bd14", label: "Migrations" },
      { id: "n2bd15", label: "Modelagem de banco real" },
    ],
    criteria: [
      { id: "n2bdc1", label: "Consigo investigar query lenta" },
      { id: "n2bdc2", label: "Consigo escolher índice adequado" },
      { id: "n2bdc3", label: "Consigo usar transactions corretamente" },
      { id: "n2bdc4", label: "Consigo explicar deadlock" },
      { id: "n2bdc5", label: "Consigo modelar um banco para uma aplicação real" },
    ]
  },
  {
    id: "n2-orm",
    icon: "🧩",
    title: "ORM e Query Builders",
    desc: "Use ORMs com consciência — sem esquecer o SQL.",
    topics: [
      { id: "n2o1", label: "Prisma" },
      { id: "n2o2", label: "Drizzle" },
      { id: "n2o3", label: "Migrations" },
      { id: "n2o4", label: "Schema" },
      { id: "n2o5", label: "Relations" },
      { id: "n2o6", label: "Transactions" },
      { id: "n2o7", label: "Query Builder" },
      { id: "n2o8", label: "Raw SQL" },
      { id: "n2o9", label: "N+1" },
      { id: "n2o10", label: "Quando usar ORM" },
      { id: "n2o11", label: "Quando não usar ORM" },
    ],
    criteria: [
      { id: "n2oc1", label: "Consigo usar ORM sem esquecer SQL" },
      { id: "n2oc2", label: "Consigo identificar N+1" },
      { id: "n2oc3", label: "Consigo decidir entre ORM e SQL" },
      { id: "n2oc4", label: "Consigo criar migrations com segurança" },
    ]
  },
  {
    id: "n2-testes",
    icon: "🧪",
    title: "Testes Profissionais",
    desc: "Testes que dão confiança para refatorar e entregar.",
    topics: [
      { id: "n2te1", label: "Unit Tests" },
      { id: "n2te2", label: "Integration Tests" },
      { id: "n2te3", label: "E2E" },
      { id: "n2te4", label: "Mocks" },
      { id: "n2te5", label: "Spies" },
      { id: "n2te6", label: "Stubs" },
      { id: "n2te7", label: "Fixtures" },
      { id: "n2te8", label: "Test Doubles" },
      { id: "n2te9", label: "Test Database" },
      { id: "n2te10", label: "Factories" },
      { id: "n2te11", label: "Coverage" },
      { id: "n2te12", label: "TDD" },
      { id: "n2te13", label: "Vitest" },
      { id: "n2te14", label: "Supertest" },
      { id: "n2te15", label: "Playwright" },
    ],
    criteria: [
      { id: "n2tec1", label: "Sei escolher o tipo de teste adequado" },
      { id: "n2tec2", label: "Consigo testar services" },
      { id: "n2tec3", label: "Consigo testar API com banco" },
      { id: "n2tec4", label: "Consigo criar testes E2E" },
      { id: "n2tec5", label: "Consigo testar erros e edge cases" },
    ]
  },
  {
    id: "n2-react-intermediario",
    icon: "⚛️",
    title: "React Intermediário",
    desc: "Composição, estado e performance no React moderno.",
    topics: [
      { id: "n2r1", label: "Composição de componentes" },
      { id: "n2r2", label: "Custom Hooks" },
      { id: "n2r3", label: "Lifting State" },
      { id: "n2r4", label: "Derived State" },
      { id: "n2r5", label: "Controlled Components" },
      { id: "n2r6", label: "Uncontrolled Components" },
      { id: "n2r7", label: "Context" },
      { id: "n2r8", label: "TanStack Query" },
      { id: "n2r9", label: "Mutations" },
      { id: "n2r10", label: "Cache" },
      { id: "n2r11", label: "Invalidation" },
      { id: "n2r12", label: "Optimistic Updates" },
      { id: "n2r13", label: "React Hook Form" },
      { id: "n2r14", label: "Zustand" },
      { id: "n2r15", label: "Error Boundaries" },
      { id: "n2r16", label: "Lazy Loading" },
      { id: "n2r17", label: "Suspense" },
      { id: "n2r18", label: "Performance básica" },
    ],
    criteria: [
      { id: "n2rc1", label: "Consigo criar custom hooks" },
      { id: "n2rc2", label: "Consigo diferenciar server state de client state" },
      { id: "n2rc3", label: "Consigo organizar estado sem exagero" },
      { id: "n2rc4", label: "Consigo trabalhar com cache" },
      { id: "n2rc5", label: "Consigo criar formulários complexos" },
    ]
  },
  {
    id: "n2-next",
    icon: "▲",
    title: "Next.js",
    desc: "O framework full stack do React: App Router, SSR e mais.",
    topics: [
      { id: "n2nx1", label: "App Router" },
      { id: "n2nx2", label: "Server Components" },
      { id: "n2nx3", label: "Client Components" },
      { id: "n2nx4", label: "Layouts" },
      { id: "n2nx5", label: "Routing" },
      { id: "n2nx6", label: "SSR" },
      { id: "n2nx7", label: "SSG" },
      { id: "n2nx8", label: "ISR" },
      { id: "n2nx9", label: "Server Actions" },
      { id: "n2nx10", label: "Middleware" },
      { id: "n2nx11", label: "Caching" },
      { id: "n2nx12", label: "Revalidation" },
      { id: "n2nx13", label: "Metadata" },
      { id: "n2nx14", label: "Autenticação" },
      { id: "n2nx15", label: "APIs no Next" },
    ],
    criteria: [
      { id: "n2nxc1", label: "Consigo explicar Server vs Client Components" },
      { id: "n2nxc2", label: "Consigo escolher entre SSR, SSG e ISR" },
      { id: "n2nxc3", label: "Consigo explicar onde cada código executa" },
      { id: "n2nxc4", label: "Consigo construir aplicação full stack simples em Next" },
      { id: "n2nxc5", label: "Consigo separar responsabilidades" },
    ]
  },
  {
    id: "n2-redis",
    icon: "🧱",
    title: "Redis",
    desc: "Cache, sessões e estruturas além do banco relacional.",
    topics: [
      { id: "n2re1", label: "Cache" },
      { id: "n2re2", label: "TTL" },
      { id: "n2re3", label: "Cache invalidation" },
      { id: "n2re4", label: "Sessions" },
      { id: "n2re5", label: "Rate Limiting" },
      { id: "n2re6", label: "Pub/Sub" },
      { id: "n2re7", label: "Locks" },
      { id: "n2re8", label: "Estruturas de dados do Redis" },
    ],
    criteria: [
      { id: "n2rec1", label: "Consigo implementar cache" },
      { id: "n2rec2", label: "Consigo definir TTL" },
      { id: "n2rec3", label: "Consigo invalidar cache" },
      { id: "n2rec4", label: "Consigo explicar quando usar Redis" },
      { id: "n2rec5", label: "Consigo explicar quando não usar Redis" },
    ]
  },
  {
    id: "n2-filas",
    icon: "📨",
    title: "Filas e Processamento Assíncrono",
    desc: "Desacople tarefas pesadas com workers e filas.",
    topics: [
      { id: "n2fi1", label: "BullMQ" },
      { id: "n2fi2", label: "Redis" },
      { id: "n2fi3", label: "Queue" },
      { id: "n2fi4", label: "Producer" },
      { id: "n2fi5", label: "Consumer" },
      { id: "n2fi6", label: "Worker" },
      { id: "n2fi7", label: "Retry" },
      { id: "n2fi8", label: "Backoff" },
      { id: "n2fi9", label: "Dead Letter Queue" },
      { id: "n2fi10", label: "Idempotência" },
      { id: "n2fi11", label: "Jobs agendados" },
      { id: "n2fi12", label: "Background Processing" },
    ],
    criteria: [
      { id: "n2fic1", label: "Consigo mover tarefa pesada para fila" },
      { id: "n2fic2", label: "Consigo criar worker" },
      { id: "n2fic3", label: "Consigo implementar retry" },
      { id: "n2fic4", label: "Consigo evitar processamento duplicado" },
    ]
  },
  {
    id: "n2-websockets",
    icon: "🔌",
    title: "WebSockets e Tempo Real",
    desc: "Comunicação bidirecional e eventos em tempo real.",
    topics: [
      { id: "n2ws1", label: "WebSocket" },
      { id: "n2ws2", label: "Polling" },
      { id: "n2ws3", label: "Long Polling" },
      { id: "n2ws4", label: "SSE" },
      { id: "n2ws5", label: "Conexão persistente" },
      { id: "n2ws6", label: "Rooms" },
      { id: "n2ws7", label: "Eventos" },
      { id: "n2ws8", label: "Reconexão" },
      { id: "n2ws9", label: "Escalabilidade" },
    ],
    criteria: [
      { id: "n2wsc1", label: "Consigo explicar HTTP vs WebSocket" },
      { id: "n2wsc2", label: "Consigo criar comunicação em tempo real" },
      { id: "n2wsc3", label: "Consigo lidar com desconexões" },
    ]
  },
  {
    id: "n2-seguranca",
    icon: "🛡️",
    title: "Segurança Web",
    desc: "Proteja sua aplicação contra os ataques mais comuns.",
    topics: [
      { id: "n2s1", label: "OWASP" },
      { id: "n2s2", label: "SQL Injection" },
      { id: "n2s3", label: "XSS" },
      { id: "n2s4", label: "CSRF" },
      { id: "n2s5", label: "SSRF" },
      { id: "n2s6", label: "Broken Access Control" },
      { id: "n2s7", label: "Brute Force" },
      { id: "n2s8", label: "Rate Limiting" },
      { id: "n2s9", label: "Secrets" },
      { id: "n2s10", label: "CORS" },
      { id: "n2s11", label: "Security Headers" },
      { id: "n2s12", label: "Input Validation" },
      { id: "n2s13", label: "Upload Seguro" },
    ],
    criteria: [
      { id: "n2sc1", label: "Consigo identificar vulnerabilidades básicas" },
      { id: "n2sc2", label: "Consigo proteger endpoints" },
      { id: "n2sc3", label: "Consigo armazenar secrets corretamente" },
      { id: "n2sc4", label: "Consigo explicar ataques web comuns" },
    ]
  },
  {
    id: "n2-docker-inter",
    icon: "🐳",
    title: "Docker Intermediário",
    desc: "Containers otimizados e stacks completas.",
    topics: [
      { id: "n2d1", label: "Multi-stage builds" },
      { id: "n2d2", label: "Healthcheck" },
      { id: "n2d3", label: "Networks" },
      { id: "n2d4", label: "Volumes" },
      { id: "n2d5", label: "Build cache" },
      { id: "n2d6", label: ".dockerignore" },
      { id: "n2d7", label: "Secrets" },
      { id: "n2d8", label: "Docker Compose avançado" },
      { id: "n2d9", label: "Containers imutáveis" },
    ],
    criteria: [
      { id: "n2dc1", label: "Consigo otimizar Dockerfile" },
      { id: "n2dc2", label: "Consigo reduzir imagem" },
      { id: "n2dc3", label: "Consigo configurar healthcheck" },
      { id: "n2dc4", label: "Consigo montar stack completa via Compose" },
    ]
  },
  {
    id: "n2-cicd",
    icon: "⚙️",
    title: "CI/CD",
    desc: "Automatize build, testes e deploy.",
    topics: [
      { id: "n2ci1", label: "GitHub Actions" },
      { id: "n2ci2", label: "Pipelines" },
      { id: "n2ci3", label: "Lint" },
      { id: "n2ci4", label: "Tests" },
      { id: "n2ci5", label: "Build" },
      { id: "n2ci6", label: "Docker Image" },
      { id: "n2ci7", label: "Registry" },
      { id: "n2ci8", label: "Deploy" },
      { id: "n2ci9", label: "Rollback" },
      { id: "n2ci10", label: "Environments" },
      { id: "n2ci11", label: "Secrets" },
    ],
    criteria: [
      { id: "n2cic1", label: "Consigo criar pipeline sozinho" },
      { id: "n2cic2", label: "Consigo impedir deploy com testes falhando" },
      { id: "n2cic3", label: "Consigo automatizar deploy" },
      { id: "n2cic4", label: "Consigo trabalhar com secrets" },
    ]
  },
  {
    id: "n2-observabilidade",
    icon: "🔭",
    title: "Observabilidade",
    desc: "Enxergue o que acontece em produção.",
    topics: [
      { id: "n2ob1", label: "Logs" },
      { id: "n2ob2", label: "Metrics" },
      { id: "n2ob3", label: "Tracing" },
      { id: "n2ob4", label: "Request ID" },
      { id: "n2ob5", label: "Correlation ID" },
      { id: "n2ob6", label: "Health Checks" },
      { id: "n2ob7", label: "Alertas" },
      { id: "n2ob8", label: "Latência" },
      { id: "n2ob9", label: "Error Rate" },
    ],
    criteria: [
      { id: "n2obc1", label: "Consigo rastrear requisição" },
      { id: "n2obc2", label: "Consigo investigar erro por logs" },
      { id: "n2obc3", label: "Consigo criar métricas básicas" },
      { id: "n2obc4", label: "Consigo identificar gargalos" },
    ]
  },
  {
    id: "n2-projeto-final",
    icon: "🏆",
    title: "Missão Final — Desenvolvedor Intermediário",
    desc: "Sistema SaaS de gerenciamento empresarial. Se todos os blocos anteriores forem base, aqui é a prova em campo.",
    topics: [
      { id: "n2pf1", label: "Autenticação (login, refresh, logout)" },
      { id: "n2pf2", label: "Organizações / multi-tenant básico" },
      { id: "n2pf3", label: "Usuários, roles e permissões" },
      { id: "n2pf4", label: "Projetos e tarefas (CRUD completo)" },
      { id: "n2pf5", label: "Comentários" },
      { id: "n2pf6", label: "Uploads" },
      { id: "n2pf7", label: "Notificações" },
      { id: "n2pf8", label: "Relatórios / listagens" },
      { id: "n2pf9", label: "Cache com Redis" },
      { id: "n2pf10", label: "Filas para tarefas em background" },
      { id: "n2pf11", label: "Testes (unit + integração + E2E)" },
      { id: "n2pf12", label: "Docker + Compose" },
      { id: "n2pf13", label: "CI/CD" },
      { id: "n2pf14", label: "Logs e health checks" },
      { id: "n2pf15", label: "Deploy em ambiente real" },
    ],
    criteria: [
      { id: "n2pfc1", label: "SaaS no ar com autenticação, permissões e CRUDs completos" },
      { id: "n2pfc2", label: "Infra com Docker, pipeline e observabilidade básica documentados" },
    ]
  },
];

// -----------------------------------------------------
//  NÍVEL 3 — AVANÇADO
// -----------------------------------------------------
const NIVEL_3_DATA = [
  {
    id: "n3-fund-arq",
    icon: "🏛️",
    title: "Fundamentos de Arquitetura de Software",
    desc: "Os princípios que guiam toda decisão arquitetural.",
    topics: [
      { id: "n3f1", label: "Acoplamento" },
      { id: "n3f2", label: "Coesão" },
      { id: "n3f3", label: "Abstração" },
      { id: "n3f4", label: "Encapsulamento" },
      { id: "n3f5", label: "Modularidade" },
      { id: "n3f6", label: "Boundaries" },
      { id: "n3f7", label: "Dependency Inversion" },
      { id: "n3f8", label: "Separation of Concerns" },
    ],
    criteria: [
      { id: "n3fc1", label: "Consigo identificar alto acoplamento e onde quebrar" },
      { id: "n3fc2", label: "Consigo desenhar boundaries coerentes entre módulos" },
    ]
  },
  {
    id: "n3-solid",
    icon: "💎",
    title: "SOLID",
    desc: "Princípios que tornam código flexível sem over-engineering.",
    topics: [
      { id: "n3s1", label: "SRP" },
      { id: "n3s2", label: "OCP" },
      { id: "n3s3", label: "LSP" },
      { id: "n3s4", label: "ISP" },
      { id: "n3s5", label: "DIP" },
      { id: "n3s6", label: "Refatoração guiada por SOLID" },
      { id: "n3s7", label: "Trade-offs" },
      { id: "n3s8", label: "Abstração desnecessária — quando não aplicar" },
    ],
    criteria: [
      { id: "n3sc1", label: "Consigo refatorar um código violando SOLID e explicar o ganho" },
      { id: "n3sc2", label: "Sei quando não abstrair" },
    ]
  },
  {
    id: "n3-patterns",
    icon: "🧩",
    title: "Design Patterns",
    desc: "Vocabulário compartilhado para problemas recorrentes.",
    topics: [
      { id: "n3p1", label: "Factory" },
      { id: "n3p2", label: "Strategy" },
      { id: "n3p3", label: "Adapter" },
      { id: "n3p4", label: "Decorator" },
      { id: "n3p5", label: "Observer" },
      { id: "n3p6", label: "Command" },
      { id: "n3p7", label: "Facade" },
      { id: "n3p8", label: "Proxy" },
      { id: "n3p9", label: "Repository" },
      { id: "n3p10", label: "Unit of Work" },
      { id: "n3p11", label: "Dependency Injection" },
    ],
    criteria: [
      { id: "n3pc1", label: "Consigo aplicar 2+ patterns justificando a escolha" },
      { id: "n3pc2", label: "Consigo diferenciar pattern de over-engineering" },
    ]
  },
  {
    id: "n3-camadas",
    icon: "🥪",
    title: "Arquitetura em Camadas",
    desc: "Separar apresentação, aplicação, domínio e infraestrutura.",
    topics: [
      { id: "n3c1", label: "Presentation" },
      { id: "n3c2", label: "Application" },
      { id: "n3c3", label: "Domain" },
      { id: "n3c4", label: "Infrastructure" },
      { id: "n3c5", label: "Dependências entre camadas" },
    ],
    criteria: [
      { id: "n3cc1", label: "Consigo organizar um projeto em camadas e explicar cada responsabilidade" },
    ]
  },
  {
    id: "n3-clean",
    icon: "✨",
    title: "Clean Architecture",
    desc: "Domínio no centro, frameworks na periferia.",
    topics: [
      { id: "n3cl1", label: "Entities" },
      { id: "n3cl2", label: "Use Cases" },
      { id: "n3cl3", label: "Adapters" },
      { id: "n3cl4", label: "Frameworks" },
      { id: "n3cl5", label: "Dependency Rule" },
      { id: "n3cl6", label: "Trade-offs" },
    ],
    criteria: [
      { id: "n3clc1", label: "Consigo desenhar um diagrama Clean e justificar as dependências" },
    ]
  },
  {
    id: "n3-hexagonal",
    icon: "⬡",
    title: "Arquitetura Hexagonal",
    desc: "Ports & Adapters para isolar o domínio.",
    topics: [
      { id: "n3h1", label: "Ports" },
      { id: "n3h2", label: "Adapters" },
      { id: "n3h3", label: "Inbound" },
      { id: "n3h4", label: "Outbound" },
      { id: "n3h5", label: "Domain" },
      { id: "n3h6", label: "Infrastructure" },
    ],
    criteria: [
      { id: "n3hc1", label: "Consigo implementar um adapter trocável (ex: trocar DB sem tocar domínio)" },
    ]
  },
  {
    id: "n3-ddd",
    icon: "🗺️",
    title: "Domain-Driven Design",
    desc: "Modelar software a partir da linguagem do negócio.",
    topics: [
      { id: "n3d1", label: "Domain" },
      { id: "n3d2", label: "Subdomain" },
      { id: "n3d3", label: "Bounded Context" },
      { id: "n3d4", label: "Ubiquitous Language" },
      { id: "n3d5", label: "Entity" },
      { id: "n3d6", label: "Value Object" },
      { id: "n3d7", label: "Aggregate" },
      { id: "n3d8", label: "Aggregate Root" },
      { id: "n3d9", label: "Domain Service" },
      { id: "n3d10", label: "Repository" },
      { id: "n3d11", label: "Domain Events" },
    ],
    criteria: [
      { id: "n3dc1", label: "Consigo modelar um bounded context com linguagem ubíqua" },
      { id: "n3dc2", label: "Consigo distinguir Entity de Value Object em um exemplo real" },
    ]
  },
  {
    id: "n3-modular",
    icon: "🧱",
    title: "Arquitetura Modular",
    desc: "Modular Monolith antes de distribuir.",
    topics: [
      { id: "n3m1", label: "Modular Monolith" },
      { id: "n3m2", label: "Boundaries" },
      { id: "n3m3", label: "Modules" },
      { id: "n3m4", label: "Internal APIs" },
      { id: "n3m5", label: "Comunicação entre módulos" },
      { id: "n3m6", label: "Dependências" },
    ],
    criteria: [
      { id: "n3mc1", label: "Consigo desenhar módulos com dependências explícitas e acoplamento baixo" },
    ]
  },
  {
    id: "n3-microservices",
    icon: "🔗",
    title: "Microservices",
    desc: "Quando quebrar, como quebrar — e quando não quebrar.",
    topics: [
      { id: "n3mi1", label: "Service boundaries" },
      { id: "n3mi2", label: "Database per service" },
      { id: "n3mi3", label: "Comunicação" },
      { id: "n3mi4", label: "Deploy independente" },
      { id: "n3mi5", label: "Service Discovery" },
      { id: "n3mi6", label: "Eventual Consistency" },
      { id: "n3mi7", label: "Vantagens" },
      { id: "n3mi8", label: "Custos" },
      { id: "n3mi9", label: "Quando não usar" },
    ],
    criteria: [
      { id: "n3mic1", label: "Consigo listar custos ocultos de microservices para um caso concreto" },
    ]
  },
  {
    id: "n3-distribuidos",
    icon: "🌐",
    title: "Sistemas Distribuídos",
    desc: "Falhas parciais, consistência e as leis da rede.",
    topics: [
      { id: "n3sd1", label: "Latency" },
      { id: "n3sd2", label: "Network Failure" },
      { id: "n3sd3", label: "Partial Failure" },
      { id: "n3sd4", label: "Consistency" },
      { id: "n3sd5", label: "Availability" },
      { id: "n3sd6", label: "Partition Tolerance" },
      { id: "n3sd7", label: "CAP Theorem" },
      { id: "n3sd8", label: "Eventual Consistency" },
      { id: "n3sd9", label: "Distributed Transactions" },
      { id: "n3sd10", label: "Idempotency" },
      { id: "n3sd11", label: "Retry" },
      { id: "n3sd12", label: "Timeout" },
      { id: "n3sd13", label: "Circuit Breaker" },
    ],
    criteria: [
      { id: "n3sdc1", label: "Consigo explicar CAP com um exemplo prático" },
      { id: "n3sdc2", label: "Consigo desenhar estratégia de retry/timeout/circuit breaker" },
    ]
  },
  {
    id: "n3-mensageria",
    icon: "📨",
    title: "Mensageria",
    desc: "Brokers, tópicos e garantias de entrega.",
    topics: [
      { id: "n3me1", label: "RabbitMQ" },
      { id: "n3me2", label: "Kafka" },
      { id: "n3me3", label: "Producer" },
      { id: "n3me4", label: "Consumer" },
      { id: "n3me5", label: "Broker" },
      { id: "n3me6", label: "Topic" },
      { id: "n3me7", label: "Partition" },
      { id: "n3me8", label: "Offset" },
      { id: "n3me9", label: "ACK" },
      { id: "n3me10", label: "Ordering" },
      { id: "n3me11", label: "Retry" },
      { id: "n3me12", label: "DLQ" },
    ],
    criteria: [
      { id: "n3mec1", label: "Consigo comparar RabbitMQ vs Kafka para um caso de uso" },
    ]
  },
  {
    id: "n3-event-driven",
    icon: "⚡",
    title: "Event-Driven Architecture",
    desc: "Eventos como espinha dorsal da integração.",
    topics: [
      { id: "n3ev1", label: "Events" },
      { id: "n3ev2", label: "Commands" },
      { id: "n3ev3", label: "Handlers" },
      { id: "n3ev4", label: "Eventual Consistency" },
      { id: "n3ev5", label: "Event Bus" },
      { id: "n3ev6", label: "Integration Events" },
    ],
    criteria: [
      { id: "n3evc1", label: "Consigo desenhar um fluxo event-driven com eventual consistency" },
    ]
  },
  {
    id: "n3-idempotencia",
    icon: "🔁",
    title: "Idempotência",
    desc: "Proteção contra duplicação — essencial em pagamentos e filas.",
    topics: [
      { id: "n3id1", label: "Idempotency Keys" },
      { id: "n3id2", label: "Proteção contra requisições duplicadas" },
      { id: "n3id3", label: "Processamento duplicado" },
      { id: "n3id4", label: "Pagamentos" },
      { id: "n3id5", label: "Filas" },
    ],
    criteria: [
      { id: "n3idc1", label: "Consigo implementar idempotency key em um endpoint crítico" },
    ]
  },
  {
    id: "n3-concorrencia",
    icon: "🏎️",
    title: "Concorrência",
    desc: "Race conditions e controle de acesso simultâneo.",
    topics: [
      { id: "n3co1", label: "Race Condition" },
      { id: "n3co2", label: "Mutex" },
      { id: "n3co3", label: "Locks" },
      { id: "n3co4", label: "Optimistic Locking" },
      { id: "n3co5", label: "Pessimistic Locking" },
      { id: "n3co6", label: "Atomic Operations" },
      { id: "n3co7", label: "Concurrency Control" },
    ],
    criteria: [
      { id: "n3coc1", label: "Consigo escolher e aplicar estratégia de locking adequada" },
    ]
  },
  {
    id: "n3-bd-avancado",
    icon: "🗄️",
    title: "Banco de Dados Avançado",
    desc: "Escalar dados: partição, replicação e planejamento de queries.",
    topics: [
      { id: "n3ba1", label: "Query Planner" },
      { id: "n3ba2", label: "Execution Plans" },
      { id: "n3ba3", label: "Partitioning" },
      { id: "n3ba4", label: "Replication" },
      { id: "n3ba5", label: "Sharding" },
      { id: "n3ba6", label: "Read Replicas" },
      { id: "n3ba7", label: "Connection Pooling" },
      { id: "n3ba8", label: "Locking" },
      { id: "n3ba9", label: "MVCC" },
    ],
    criteria: [
      { id: "n3bac1", label: "Consigo ler um execution plan e otimizar query crítica" },
    ]
  },
  {
    id: "n3-cache-avancado",
    icon: "🧊",
    title: "Cache Avançado",
    desc: "Estratégias de cache e armadilhas de invalidação.",
    topics: [
      { id: "n3ca1", label: "Cache Aside" },
      { id: "n3ca2", label: "Write Through" },
      { id: "n3ca3", label: "Write Behind" },
      { id: "n3ca4", label: "TTL" },
      { id: "n3ca5", label: "Invalidation" },
      { id: "n3ca6", label: "Distributed Cache" },
      { id: "n3ca7", label: "Cache Stampede" },
    ],
    criteria: [
      { id: "n3cac1", label: "Consigo escolher estratégia de cache e lidar com stampede" },
    ]
  },
  {
    id: "n3-performance",
    icon: "🚀",
    title: "Performance",
    desc: "Backend e frontend sob lupa: profiling e Core Web Vitals.",
    topics: [
      { id: "n3pe1", label: "Profiling" },
      { id: "n3pe2", label: "CPU" },
      { id: "n3pe3", label: "Memory" },
      { id: "n3pe4", label: "Event Loop" },
      { id: "n3pe5", label: "Queries" },
      { id: "n3pe6", label: "Network" },
      { id: "n3pe7", label: "Serialization" },
      { id: "n3pe8", label: "Bundle Size" },
      { id: "n3pe9", label: "Rendering" },
      { id: "n3pe10", label: "Core Web Vitals" },
      { id: "n3pe11", label: "Code Splitting" },
      { id: "n3pe12", label: "Lazy Loading" },
      { id: "n3pe13", label: "Caching" },
    ],
    criteria: [
      { id: "n3pec1", label: "Consigo medir e otimizar latência/bundle de um caso real" },
    ]
  },
  {
    id: "n3-observabilidade-av",
    icon: "🔭",
    title: "Observabilidade Avançada",
    desc: "Tracing distribuído e SLOs que importam.",
    topics: [
      { id: "n3ob1", label: "OpenTelemetry" },
      { id: "n3ob2", label: "Distributed Tracing" },
      { id: "n3ob3", label: "Structured Logging" },
      { id: "n3ob4", label: "Metrics" },
      { id: "n3ob5", label: "Dashboards" },
      { id: "n3ob6", label: "Alerting" },
      { id: "n3ob7", label: "SLI" },
      { id: "n3ob8", label: "SLO" },
      { id: "n3ob9", label: "SLA" },
    ],
    criteria: [
      { id: "n3obc1", label: "Consigo definir SLI/SLO e instrumentar uma aplicação" },
    ]
  },
  {
    id: "n3-resiliencia",
    icon: "🛡️",
    title: "Resiliência",
    desc: "Falhar com graça e recuperar com controle.",
    topics: [
      { id: "n3re1", label: "Retry" },
      { id: "n3re2", label: "Timeout" },
      { id: "n3re3", label: "Circuit Breaker" },
      { id: "n3re4", label: "Bulkhead" },
      { id: "n3re5", label: "Fallback" },
      { id: "n3re6", label: "Rate Limiting" },
    ],
    criteria: [
      { id: "n3rec1", label: "Consigo implementar circuit breaker e fallback em um serviço crítico" },
    ]
  },
  {
    id: "n3-k8s",
    icon: "☸️",
    title: "Kubernetes",
    desc: "Orquestração para escalar com confiança.",
    topics: [
      { id: "n3k1", label: "Pods" },
      { id: "n3k2", label: "Deployments" },
      { id: "n3k3", label: "Services" },
      { id: "n3k4", label: "Ingress" },
      { id: "n3k5", label: "ConfigMaps" },
      { id: "n3k6", label: "Secrets" },
      { id: "n3k7", label: "Volumes" },
      { id: "n3k8", label: "Namespaces" },
      { id: "n3k9", label: "Replicas" },
      { id: "n3k10", label: "Health Checks" },
      { id: "n3k11", label: "Autoscaling" },
    ],
    criteria: [
      { id: "n3kc1", label: "Consigo subir uma aplicação em K8s com health checks e replicas" },
    ]
  },
  {
    id: "n3-cloud",
    icon: "☁️",
    title: "Cloud",
    desc: "AWS (ou equivalente) na prática: compute, rede, storage e IAM.",
    topics: [
      { id: "n3cld1", label: "Compute" },
      { id: "n3cld2", label: "Networking" },
      { id: "n3cld3", label: "Storage" },
      { id: "n3cld4", label: "Databases" },
      { id: "n3cld5", label: "IAM" },
      { id: "n3cld6", label: "Load Balancer" },
      { id: "n3cld7", label: "DNS" },
      { id: "n3cld8", label: "CDN" },
      { id: "n3cld9", label: "Queues" },
      { id: "n3cld10", label: "Monitoring" },
    ],
    criteria: [
      { id: "n3cldc1", label: "Consigo desenhar infra mínima na cloud com IAM e rede" },
    ]
  },
  {
    id: "n3-iac",
    icon: "🏗️",
    title: "Infrastructure as Code",
    desc: "Terraform e ambientes reproduzíveis.",
    topics: [
      { id: "n3iac1", label: "Terraform" },
      { id: "n3iac2", label: "Environments" },
      { id: "n3iac3", label: "State" },
      { id: "n3iac4", label: "Modules" },
      { id: "n3iac5", label: "Provisioning" },
    ],
    criteria: [
      { id: "n3iacc1", label: "Consigo provisionar infra com Terraform e gerenciar state" },
    ]
  },
  {
    id: "n3-arq-cloud",
    icon: "🌩️",
    title: "Arquitetura Cloud",
    desc: "Conectar CDN, LB, app, cache, DB, filas e workers.",
    topics: [
      { id: "n3ac1", label: "CDN" },
      { id: "n3ac2", label: "Load Balancer" },
      { id: "n3ac3", label: "Application" },
      { id: "n3ac4", label: "Cache" },
      { id: "n3ac5", label: "Database" },
      { id: "n3ac6", label: "Queue" },
      { id: "n3ac7", label: "Workers" },
    ],
    criteria: [
      { id: "n3acc1", label: "Consigo desenhar arquitetura completa justificando cada componente" },
    ]
  },
  {
    id: "n3-system-design",
    icon: "📐",
    title: "System Design",
    desc: "Pratique projetando sistemas reais sob restrições.",
    topics: [
      { id: "n3sdg1", label: "URL Shortener" },
      { id: "n3sdg2", label: "Chat" },
      { id: "n3sdg3", label: "Feed" },
      { id: "n3sdg4", label: "Sistema de Pagamentos" },
      { id: "n3sdg5", label: "Upload de Arquivos" },
      { id: "n3sdg6", label: "Sistema de Notificações" },
      { id: "n3sdg7", label: "Marketplace" },
      { id: "n3sdg8", label: "Considerar requisitos, capacidade, APIs, banco, cache, filas, storage, consistência, disponibilidade e escala" },
    ],
    criteria: [
      { id: "n3sdgc1", label: "Consigo conduzir um design completo de um desses sistemas justificando trade-offs" },
    ]
  },
  {
    id: "n3-seg-avancada",
    icon: "🔒",
    title: "Segurança Avançada",
    desc: "Threat modeling, criptografia e princípios de menor privilégio.",
    topics: [
      { id: "n3sg1", label: "Threat Modeling" },
      { id: "n3sg2", label: "OWASP" },
      { id: "n3sg3", label: "Authentication Flows" },
      { id: "n3sg4", label: "Secrets Management" },
      { id: "n3sg5", label: "Encryption at Rest" },
      { id: "n3sg6", label: "Encryption in Transit" },
      { id: "n3sg7", label: "Authorization Models" },
      { id: "n3sg8", label: "Audit Logs" },
      { id: "n3sg9", label: "Least Privilege" },
    ],
    criteria: [
      { id: "n3sgc1", label: "Consigo fazer threat modeling básico de uma feature" },
    ]
  },
  {
    id: "n3-times",
    icon: "🤝",
    title: "Engenharia de Software em Times",
    desc: "Processos que sustentam equipes e releases.",
    topics: [
      { id: "n3ti1", label: "Code Review" },
      { id: "n3ti2", label: "ADR" },
      { id: "n3ti3", label: "RFC" },
      { id: "n3ti4", label: "Documentação" },
      { id: "n3ti5", label: "Migrations seguras" },
      { id: "n3ti6", label: "Feature Flags" },
      { id: "n3ti7", label: "Backward Compatibility" },
      { id: "n3ti8", label: "Versionamento" },
      { id: "n3ti9", label: "Rollout" },
      { id: "n3ti10", label: "Rollback" },
    ],
    criteria: [
      { id: "n3tic1", label: "Consigo escrever ADR/RFC e planejar rollout seguro com feature flag" },
    ]
  },
  {
    id: "n3-segunda-stack",
    icon: "🔀",
    title: "Segunda e Terceira Stack",
    desc: "Aplicar os mesmos princípios em Java/Spring e Python/Django ou FastAPI — sem reaprender programação.",
    topics: [
      { id: "n3st1", label: "Java + Spring Boot — aplicar fundamentos em nova stack" },
      { id: "n3st2", label: "Python + Django ou FastAPI — aplicar fundamentos em nova stack" },
      { id: "n3st3", label: "Comparar decisões arquiteturais entre stacks" },
    ],
    criteria: [
      { id: "n3stc1", label: "Consigo transportar um design entre stacks diferentes justificando adaptações" },
    ]
  },
  {
    id: "n3-projeto-final",
    icon: "🏆",
    title: "Missão Final — Arquiteto da Jornada",
    desc: "Plataforma SaaS multi-tenant completa: o coroar da jornada.",
    topics: [
      { id: "n3pf1", label: "API Gateway" },
      { id: "n3pf2", label: "Auth" },
      { id: "n3pf3", label: "Users / Organizations / Projects" },
      { id: "n3pf4", label: "Billing" },
      { id: "n3pf5", label: "Notifications / Files / Reports / Audit" },
      { id: "n3pf6", label: "PostgreSQL + Redis + Queue + Workers + Events + Cache" },
      { id: "n3pf7", label: "Observabilidade (logs, metrics, tracing)" },
      { id: "n3pf8", label: "CI/CD + Docker + Kubernetes + Cloud" },
      { id: "n3pf9", label: "Testes e segurança" },
      { id: "n3pf10", label: "Documentação arquitetural (ADRs/diagramas)" },
    ],
    criteria: [
      { id: "n3pfc1", label: "Plataforma multi-tenant com gateway, billing e domínios bem delimitados" },
      { id: "n3pfc2", label: "Infra e observabilidade documentadas com decisões arquiteturais explícitas" },
    ]
  },
];

// Compatibilidade: TRILHA_DATA continua sendo o Nível 1 (para código legado e migração)
const TRILHA_DATA = NIVEL_1_DATA;

// Mapa por key para acesso rápido
const JOURNEY_DATA = {
  "iniciante": NIVEL_1_DATA,
  "intermediario": NIVEL_2_DATA,
  "avancado": NIVEL_3_DATA,
};

const LEVEL_CONFIG = [
  { min: 0,  title: "Aprendiz",   icon: "🌱", quote: "Toda lenda começa com um primeiro passo." },
  { min: 15, title: "Escudeiro",  icon: "🛡️", quote: "O escudo pesa, mas você já sabe carregá-lo." },
  { min: 35, title: "Aventureiro",icon: "🗺️", quote: "O mapa se abre — a estrada chama por você." },
  { min: 55, title: "Cavaleiro",  icon: "⚔️", quote: "Sua lâmina encontrou propósito. Avance!" },
  { min: 75, title: "Guardião",   icon: "🏹", quote: "Você guarda o conhecimento e guia outros." },
  { min: 90, title: "Mestre",     icon: "👑", quote: "Lenda viva da trilha. O reino o reconhece!" },
];

// =====================================================
//  PROJETOS DE CONSOLIDAÇÃO (1 obrigatório + 1 desafio por nível)
// =====================================================
const CONSOLIDATION_PROJECTS = {
  iniciante: {
    mandatory: {
      id: "n1-proj-obrigatorio",
      kind: "mandatory",
      title: "Sistema de Gestão de Tarefas",
      subtitle: "Missão Principal",
      icon: "🛡️",
      image: "public/images/fantasy/quests/level-1-main.webp",
      imageAlt: "Oficina da guilda com mapas e ferramentas — missão importante e acolhedora",
      objective: "Consolidar toda a base Full Stack aprendida no Nível 1.",
      stack: ["React", "TypeScript", "Fastify", "PostgreSQL", "Docker"],
      features: [
        "cadastro de usuário",
        "login",
        "autenticação",
        "usuários",
        "projetos",
        "tarefas",
        "status",
        "prioridades",
        "comentários",
        "filtros",
        "dashboard simples",
        "API REST",
        "persistência em banco",
        "frontend consumindo backend",
        "tratamento básico de erros",
        "Docker Compose",
        "deploy simples",
      ],
      criteria: [
        { id: "n1m1", label: "Modelei o banco sozinho" },
        { id: "n1m2", label: "Defini os principais endpoints" },
        { id: "n1m3", label: "Criei o backend" },
        { id: "n1m4", label: "Criei o frontend" },
        { id: "n1m5", label: "Integrei frontend e backend" },
        { id: "n1m6", label: "Implementei autenticação" },
        { id: "n1m7", label: "Persisti dados no PostgreSQL" },
        { id: "n1m8", label: "Dockerizei a aplicação" },
        { id: "n1m9", label: "Fiz deploy" },
        { id: "n1m10", label: "Consigo explicar toda a arquitetura" },
        { id: "n1m11", label: "Consigo explicar o fluxo de uma request" },
        { id: "n1m12", label: "Consigo corrigir bugs básicos sozinho" },
        { id: "n1m13", label: "Consigo explicar por que cada tecnologia foi usada" },
      ],
      statusLabel: "Status do projeto",
    },
    challenge: {
      id: "n1-proj-desafio",
      kind: "challenge",
      title: "Sistema Financeiro Pessoal",
      subtitle: "Missão Desafio — Opcional",
      badge: "Projeto opcional para reforço de domínio",
      icon: "⚔️",
      image: "public/images/fantasy/quests/level-1-challenge.webp",
      imageAlt: "Tesouraria medieval light fantasy com livros-caixa, moedas e vista para o reino",
      objective: "Provar que consigo reutilizar os conceitos aprendidos em outro domínio sem simplesmente copiar o projeto anterior.",
      features: [
        "usuários",
        "login",
        "contas",
        "receitas",
        "despesas",
        "categorias",
        "saldo",
        "filtros por período",
        "resumo mensal",
        "dashboard",
        "gráficos simples",
        "persistência",
        "API REST",
        "frontend",
        "Docker",
        "deploy",
      ],
      criteria: [
        { id: "n1d1", label: "Modelei o banco sem copiar o projeto anterior" },
        { id: "n1d2", label: "Defini a API sozinho" },
        { id: "n1d3", label: "Organizei frontend e backend" },
        { id: "n1d4", label: "Implementei filtros" },
        { id: "n1d5", label: "Implementei cálculo de saldo" },
        { id: "n1d6", label: "Fiz integração completa" },
        { id: "n1d7", label: "Fiz deploy" },
        { id: "n1d8", label: "Consigo explicar as diferenças arquiteturais em relação ao projeto obrigatório" },
      ],
    },
  },
  intermediario: {
    mandatory: {
      id: "n2-proj-obrigatorio",
      kind: "mandatory",
      title: "SaaS de Gestão Empresarial",
      subtitle: "Missão Principal",
      icon: "👑",
      image: "public/images/fantasy/quests/level-2-main.webp",
      imageAlt: "Grande biblioteca e fortaleza com luz de vitral — missão de engenharia",
      objective: "Consolidar os conceitos de aplicações profissionais, robustas, testáveis, seguras e preparadas para crescer.",
      stack: ["React ou Next.js", "TypeScript", "Fastify", "PostgreSQL", "Redis", "BullMQ", "Docker", "GitHub Actions"],
      features: [
        "organizações",
        "usuários",
        "autenticação",
        "refresh token",
        "roles",
        "permissions",
        "RBAC",
        "projetos",
        "tarefas",
        "comentários",
        "uploads",
        "notificações",
        "relatórios",
        "paginação",
        "filtros",
        "cache",
        "filas",
        "background jobs",
        "logs estruturados",
        "health checks",
        "tratamento global de erros",
        "testes unitários",
        "testes de integração",
        "testes E2E",
        "CI/CD",
        "deploy",
      ],
      criteria: [
        { id: "cp-n2m1", label: "Estruturei o backend por módulos" },
        { id: "cp-n2m2", label: "Implementei autenticação completa" },
        { id: "cp-n2m3", label: "Implementei autorização por roles/permissões" },
        { id: "cp-n2m4", label: "Utilizei cache de forma consciente" },
        { id: "cp-n2m5", label: "Implementei fila e worker" },
        { id: "cp-n2m6", label: "Implementei retry" },
        { id: "cp-n2m7", label: "Evitei processamento duplicado" },
        { id: "cp-n2m8", label: "Criei testes unitários" },
        { id: "cp-n2m9", label: "Criei testes de integração" },
        { id: "cp-n2m10", label: "Criei pelo menos um fluxo E2E" },
        { id: "cp-n2m11", label: "Configurei logs estruturados" },
        { id: "cp-n2m12", label: "Configurei health checks" },
        { id: "cp-n2m13", label: "Criei pipeline CI/CD" },
        { id: "cp-n2m14", label: "Automatizei build/test/deploy" },
        { id: "cp-n2m15", label: "Consigo investigar problemas através de logs" },
        { id: "cp-n2m16", label: "Consigo explicar os trade-offs principais da arquitetura" },
      ],
      statusLabel: "Status",
    },
    challenge: {
      id: "n2-proj-desafio",
      kind: "challenge",
      title: "Plataforma de Atendimento em Tempo Real",
      subtitle: "Missão Desafio — Opcional",
      badge: "Projeto opcional para reforço de domínio",
      icon: "🔔",
      image: "public/images/fantasy/quests/level-2-challenge.webp",
      imageAlt: "Salão da guilda com mensageiros e sinos — desafio em tempo real",
      objective: "Aplicar conceitos que não aparecem normalmente em um CRUD tradicional.",
      features: [
        "usuários",
        "atendentes",
        "autenticação",
        "permissões",
        "filas de atendimento",
        "abertura de atendimento",
        "chat em tempo real",
        "WebSocket",
        "status online/offline",
        "salas",
        "notificações",
        "histórico de conversas",
        "Redis",
        "cache",
        "background jobs",
        "reconexão",
        "métricas simples",
      ],
      criteria: [
        { id: "cp-n2d1", label: "Implementei comunicação em tempo real" },
        { id: "cp-n2d2", label: "Consigo explicar HTTP vs WebSocket" },
        { id: "cp-n2d3", label: "Implementei reconexão" },
        { id: "cp-n2d4", label: "Implementei histórico" },
        { id: "cp-n2d5", label: "Usei Redis com propósito claro" },
        { id: "cp-n2d6", label: "Separei processamento assíncrono" },
        { id: "cp-n2d7", label: "Tratei erros de conexão" },
        { id: "cp-n2d8", label: "Consigo explicar como escalaria o sistema" },
      ],
    },
  },
  avancado: {
    mandatory: {
      id: "n3-proj-obrigatorio",
      kind: "mandatory",
      title: "Plataforma SaaS Multi-tenant",
      subtitle: "Missão Principal",
      icon: "🏰",
      image: "public/images/fantasy/quests/level-3-main.webp",
      imageAlt: "Cidade fantástica e castelo majestoso sob luz dourada — grande conquista",
      objective: "Consolidar arquitetura, sistemas distribuídos, resiliência, escalabilidade, observabilidade e decisões de engenharia. Foco em arquitetura e justificativa das decisões — sem complexidade artificial.",
      stack: ["PostgreSQL", "Redis", "filas/workers/eventos", "mensageria", "cache", "observabilidade", "Docker", "Kubernetes", "Cloud", "Terraform"],
      features: [
        "API Gateway",
        "Auth",
        "Users",
        "Organizations",
        "Projects",
        "Billing",
        "Files",
        "Notifications",
        "Reports",
        "Audit",
        "PostgreSQL + Redis + filas + workers + eventos + cache",
        "idempotência, retries, DLQ",
        "observabilidade (logs estruturados, tracing, métricas)",
        "CI/CD + Docker + Kubernetes + Cloud",
        "Terraform + testes + segurança + documentação arquitetural",
      ],
      criteria: [
        { id: "cp-n3m1", label: "Defini claramente os módulos/domínios" },
        { id: "cp-n3m2", label: "Consigo justificar os boundaries" },
        { id: "cp-n3m3", label: "Consigo explicar as dependências" },
        { id: "cp-n3m4", label: "Consigo explicar onde usar comunicação síncrona" },
        { id: "cp-n3m5", label: "Consigo explicar onde usar comunicação assíncrona" },
        { id: "cp-n3m6", label: "Implementei eventos" },
        { id: "cp-n3m7", label: "Implementei idempotência onde necessário" },
        { id: "cp-n3m8", label: "Implementei retry controlado" },
        { id: "cp-n3m9", label: "Implementei DLQ ou estratégia equivalente" },
        { id: "cp-n3m10", label: "Implementei observabilidade" },
        { id: "cp-n3m11", label: "Consigo rastrear uma requisição" },
        { id: "cp-n3m12", label: "Consigo explicar estratégia de cache" },
        { id: "cp-n3m13", label: "Consigo explicar consistência" },
        { id: "cp-n3m14", label: "Consigo explicar os principais gargalos" },
        { id: "cp-n3m15", label: "Consigo explicar como o sistema reagiria a falhas" },
        { id: "cp-n3m16", label: "Documentei decisões arquiteturais" },
        { id: "cp-n3m17", label: "Criei pelo menos alguns ADRs" },
        { id: "cp-n3m18", label: "Consigo justificar por que não usei determinadas tecnologias" },
        { id: "cp-n3m19", label: "Consigo explicar os trade-offs da arquitetura" },
      ],
      statusLabel: "Status",
    },
    challenge: {
      id: "n3-proj-desafio",
      kind: "challenge",
      title: "Sistema de Pagamentos Distribuído",
      subtitle: "Missão Desafio — Opcional",
      badge: "Projeto opcional — desafio avançado",
      icon: "💎",
      image: "public/images/fantasy/quests/level-3-challenge.webp",
      imageAlt: "Cofre rúnico e ponte de cristal sobre cachoeira — desafio avançado e luminoso",
      objective: "Treinar problemas típicos de sistemas críticos e distribuídos. Simulação educacional — sem pagamentos reais.",
      features: [
        "criação de pagamento fictício",
        "processamento assíncrono",
        "webhooks simulados",
        "idempotency keys",
        "retries / backoff",
        "filas / DLQ / eventos",
        "auditoria / reconciliação / antifraude fictício",
        "tracing / métricas / circuit breaker / timeout / fallback / logs estruturados",
      ],
      problems: [
        "Requisição duplicada — como evitar processar o mesmo pagamento duas vezes?",
        "Falha de rede — e se a resposta não chegar após processar?",
        "Worker fora do ar — como reprocessar a mensagem?",
        "Dependência indisponível — quando usar retry? Quando parar?",
        "Evento com erro — como usar DLQ?",
        "Estado divergente — como reconciliar dados?",
      ],
      criteria: [
        { id: "cp-n3d1", label: "Implementei idempotência" },
        { id: "cp-n3d2", label: "Consigo explicar duplicate delivery" },
        { id: "cp-n3d3", label: "Implementei retry com estratégia" },
        { id: "cp-n3d4", label: "Implementei timeout" },
        { id: "cp-n3d5", label: "Implementei DLQ" },
        { id: "cp-n3d6", label: "Implementei reconciliação" },
        { id: "cp-n3d7", label: "Consigo explicar eventual consistency" },
        { id: "cp-n3d8", label: "Consigo explicar race conditions possíveis" },
        { id: "cp-n3d9", label: "Implementei observabilidade" },
        { id: "cp-n3d10", label: "Consigo diagnosticar falhas simuladas" },
        { id: "cp-n3d11", label: "Documentei os principais trade-offs" },
      ],
    },
  },
};

const BLOCK_QUOTES = {
  "fundamentos": "A base foi lançada. Nenhuma torre cai com alicerces fortes!",
  "js-essencial": "A lâmina de JavaScript agora obedece sua mão!",
  "assincronismo": "Você dobrou o tempo a seu favor. O fluxo é seu aliado!",
  "web-http": "Os correios do reino não têm segredos para você!",
  "node-sem-framework": "Você forjou um servidor com as próprias mãos!",
  "banco-sql": "Os arquivos do castelo estão em ordem. Dados sob seu comando!",
  "backend-framework": "Muralhas erguidas! Seu backend resiste ao cerco!",
  "typescript": "Armadura rúnica equipada. Nenhum tipo te escapa!",
  "frontend-sem-framework": "Você moldou a face do reino sem magia emprestada!",
  "react": "Componentes conjurados! A interface ganha vida!",
  "docker-infra": "Seu exército cabe em um container. Pronto para marchar!",
  "git-testes-deploy": "Estandarte fincado em produção. Sua lenda é pública!",
  // Nível 2
  "n2-ts-avancado": "Tipos como runas — precisos e poderosos!",
  "n2-backend-profissional": "Seu castelo agora tem corredores, portões e guardas organizados!",
  "n2-auth": "As chaves do reino estão seguras. Nenhum intruso passa!",
  "n2-bd-intermediario": "Você lê o campo de batalha dos dados como um estrategista!",
  "n2-orm": "Você empunha ORMs sem esquecer a lâmina do SQL!",
  "n2-testes": "Cada teste é um escudo contra o caos. Sua defesa é sólida!",
  "n2-react-intermediario": "Seus feitiços React agora tecem interfaces resilientes!",
  "n2-next": "Portais entre servidor e cliente sob seu comando!",
  "n2-redis": "Memória veloz como o vento — cache dominado!",
  "n2-filas": "Tarefas marcham em fila, sem atropelos!",
  "n2-websockets": "Conexão viva, como corvos mensageiros instantâneos!",
  "n2-seguranca": "Muralhas reforçadas contra as artes sombrias!",
  "n2-docker-inter": "Seus containers são fortalezas compactas!",
  "n2-cicd": "A forja trabalha sozinha — entrega contínua conquistada!",
  "n2-observabilidade": "Olhos em toda parte. Nada escapa ao seu vigiar!",
  "n2-projeto-final": "SaaS erguido — você forjou um burgo próspero!",
  // Nível 3
  "n3-fund-arq": "Os alicerces invisíveis agora são visíveis a você!",
  "n3-solid": "Princípios como leis do reino — justos e equilibrados!",
  "n3-patterns": "Cada padrão, uma formação de batalha dominada!",
  "n3-clean": "O domínio no centro, como o trono na sala do castelo!",
  "n3-ddd": "A linguagem do domínio agora é sua língua nativa!",
  "n3-distribuidos": "Você navega mares distribuídos sem temer a tempestade!",
  "n3-mensageria": "Mensageiros incansáveis cruzam seus domínios!",
  "n3-performance": "Velocidade e elegância — sua marca de arquiteto!",
  "n3-k8s": "Seu exército escala sob estandartes orquestrados!",
  "n3-system-design": "Você projeta reinos que suportam multidões!",
  "n3-projeto-final": "Arquiteto do Reino — a jornada principal foi completada!",
};
